purpose of this notebook is to evaluate on the static embedding model `minishlab/potion-retrieval-32M`

In [1]:
from model2vec import StaticModel
from sentence_transformers import SentenceTransformer
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [2]:
from datasets import load_dataset, DatasetDict

def load_data(repo="frankjc2022/semantic-history-search"):

    docs = load_dataset(repo, name="docs")["train"]
    queries = load_dataset(repo, name="queries")["train"]
    qrels = load_dataset(repo, name="qrels")["train"]
    
    return DatasetDict(docs=docs, queries=queries, qrels=qrels)

ds = load_data()
docs = ds["docs"].to_pandas()
queries = ds["queries"].to_pandas()
qrels = ds["qrels"].to_pandas()
query_pairs = queries.merge(qrels[["query_id", "doc_id", "relevance", "rank"]], on="query_id").merge(docs[["doc_id", "url"]], on="doc_id").drop_duplicates()

# query_pairs.loc[query_pairs["is_multi"]==True]

In [3]:
persona_name = "025_creative_hobbyist"
# persona_name = "chidam"

# MODEL_NAME = "Xenova/all-MiniLM-L6-v2" 
MODEL_NAME = "minishlab/potion-retrieval-32M"

GOLDEN_QUERY_COLS = ["search_query","url"]
PROFILE_COLS = ["url", "title", "description", "frecency", "last_visit_date"] #"url_hash"

# PROFILE_FILENAMES = {
#     "creative_hobyist": {
#         "golden_query_data" : "../test_data/creative_hobyist_profile_golden_queries.csv",
#         "profile_data": "../test_data/creative_hobbyist.csv"
#     },
#     # "chidam": {
#     #     "golden_query_data" : "../data/chidam_golden_query.csv",
#     #     "profile_data": "../data/history_output_file.csv"
#     # }
# }
# PROFILE_FILENAME = "../data/chidam_golden_query.csv"

In [4]:
def get_model(MODEL_NAME):
    if MODEL_NAME == "Xenova/all-MiniLM-L6-v2":
        return SentenceTransformer("all-MiniLM-L6-v2")
    elif MODEL_NAME == "minishlab/potion-retrieval-32M":
        return StaticModel.from_pretrained("minishlab/potion-retrieval-32M")

def get_profile_filenames(persona_name):
    # if persona_name not in PROFILE_FILENAMES.keys():
    #     return ValueError(f"persona_name entered not in {list(PROFILE_FILENAMES.keys())}")
    # golden_queries_df = pd.read_csv(PROFILE_FILENAMES[persona_name]['golden_query_data'])[GOLDEN_QUERY_COLS]
    # profile_df = pd.read_csv(PROFILE_FILENAMES[persona_name]["profile_data"])
    #[PROFILE_COLS]

    profile_df = docs.loc[docs["profile"]==persona_name]
    golden_queries_df = query_pairs.loc[query_pairs["profile"]==persona_name]
    
    return golden_queries_df, profile_df

In [5]:
model = get_model(MODEL_NAME)

In [6]:
golden_queries_df, profile_df = get_profile_filenames(persona_name)
golden_queries_df

,query_id,search_query,profile,profile_id,is_temporal,is_multi,variant,ref_datetime_iso,doc_id,relevance,rank,url
2500,177fd25d37deb5f7,Best mosquito repellent outdoor,025_creative_hobbyist,944346ce7b090355,False,False,base,,8eea7bb8edd43f0f,1,1,http://www.wikihow.com/Get-Rid-of-Mosquitoes-i...
2501,5f3ca5774311ff47,How to get rid of heat stains on wood,025_creative_hobbyist,944346ce7b090355,False,False,base,,c9c78eebd35d316e,1,1,http://tipnut.com/diy-how-to-remove-white-heat...
2502,4401edf823ba603a,Zucchini recipes,025_creative_hobbyist,944346ce7b090355,False,False,base,,9d03a87c724f246f,1,1,http://startcooking.com/how-to-zucchini
2503,88be8c028c7cd5ee,Planting grass,025_creative_hobbyist,944346ce7b090355,False,False,base,,d7d50a3d458ce208,1,1,http://www.wikihow.com/Grow-Pampas-Grass
2504,1050d6bc10ac7ae3,Hamstring remedies,025_creative_hobbyist,944346ce7b090355,False,False,base,,bd3454d78d774133,1,1,http://www.runnersworld.com/for-beginners-only...
2505,4d30a5472ad4cb96,Organic fertilizers,025_creative_hobbyist,944346ce7b090355,False,False,base,,609ec7a855d96e0a,1,1,http://www.sunset.com/garden/garden-basics/cra...
2506,ee7ed0b2b3aebf92,Whats a choir,025_creative_hobbyist,944346ce7b090355,False,False,base,,c58e818b0211a06b,1,1,https://simple.wikipedia.org/wiki/Choir_(music)
2507,9da5f91e391800d8,Make money from music,025_creative_hobbyist,944346ce7b090355,False,False,base,,07e5bb5a4fce58f5,1,1,http://hiphopmakers.com/how-to-sell-beats-onli...
2508,e250e7d407621cd6,Chlorine for pool,025_creative_hobbyist,944346ce7b090355,False,False,base,,ec5d7c6332babf04,1,1,https://www.inyopools.com/blog/what-type-of-po...
2509,dd4e5c060b177dcd,Patio decoration,025_creative_hobbyist,944346ce7b090355,False,False,base,,4964380a087e8262,1,1,https://www.landscapingnetwork.com/patios/conc...
2510,2d8d3730e032b054,Gardening tips,025_creative_hobbyist,944346ce7b090355,False,False,base,,07381faeb57ce8b5,1,1,http://www.gardeningknowhow.com/edible/vegetab...
2511,d33f6c9060add7bb,Replace sliding door,025_creative_hobbyist,944346ce7b090355,False,False,base,,146b768fbe797a85,1,1,http://www.swisco.com/guides/view35
2512,5fa5a9af6a8a3c38,Window insulation,025_creative_hobbyist,944346ce7b090355,False,False,base,,7cb9deb3a368858f,1,1,http://home.howstuffworks.com/home-improvement...
2513,d5efeb7e730b0fbb,Yerba tea benefits,025_creative_hobbyist,944346ce7b090355,False,False,base,,fcb5fb74b3613ef7,1,1,http://www.fitday.com/fitness-articles/nutriti...
2514,0d548069c22897d5,How to grow onions,025_creative_hobbyist,944346ce7b090355,False,False,base,,67e7bc231361ad5f,1,1,http://strongertogether.coop/fresh-from-the-so...
2515,75391d62da3f0d3f,Keto breakfast,025_creative_hobbyist,944346ce7b090355,False,False,base,,f572c47373ca6a27,1,1,https://www.ruled.me/keto-bacon-and-eggs/
2516,0b056f4aefe83ca9,Get started with running,025_creative_hobbyist,944346ce7b090355,False,False,base,,3663aa39d34e47ab,1,1,https://www.verywell.com/tips-for-running-in-t...
2517,ab7ba35a66ae3d07,Making tasty brussels,025_creative_hobbyist,944346ce7b090355,False,False,base,,64c370bcc1de4ad8,1,1,https://www.healyounaturally.com/6-benefits-br...
2518,d165900b3c4ea9d9,Modern living room,025_creative_hobbyist,944346ce7b090355,False,False,base,,ed6eef853ac87451,1,1,http://www.wikihow.com/Decorate-a-Living-Room
2519,75f5e6b6352678fe,Wall prep tips for painting,025_creative_hobbyist,944346ce7b090355,False,False,base,,718c1dd14d93a851,1,1,http://homeguides.sfgate.com/prepare-walls-pai...
2520,d1d117bb742962d4,Best way to produce charcoal,025_creative_hobbyist,944346ce7b090355,False,False,base,,3a43b403f6ca882c,1,1,http://www.wikihow.com/Make-Charcoal
2521,f557006fe4418a28,How to water plants in non-draining pots,025_creative_hobbyist,944346ce7b090355,False,False,base,,091b8c41c45e26d5,1,1,http://homeguides.sfgate.com/plant-pot-holes-4...
2522,b41ea5c0dcee833d,Are tulips and daffodils cold hardy,025_creative_hobbyist,944346ce7b090355,False,False,base,,8abbd2faaabafe4d,1,1,http://www.ehow.com/info_8362341_tulips-daffod...
2523,a2dceaf48504b82c,How to tell if a potato is rotten,025_creative_hobbyist,944346ce7b090355,False,False,base,,6e2a3d7624dd5efb,1,1,https://www.leaf.tv/articles/how-to-know-when-...
2524,4856e021d43df100,put out a charcoal fire,025_creative_hobbyist,944346ce7b090355,False,False,base,,f64059cd13743e41,1,1,http://homeguides.sfgate.com/extinguish-charco...
2525,4d3f26d02b48e69f,Best time to harvest garlic,025_creative_hobbyist,944346ce7b090355,False,False,base,,611c71d1ce7c4a3d,1,1,https://www.thespruce.com/harvesting-garlic-14...
2526,1af6cbea4c5b939b,How to set up for a painting job,025_creative_hobbyist,944346ce7b090355,False,False,base,,b2ebbefdde0908d1,1,1,https://www.thespruce.com/essential-painting-s...
2527,adfa03c6869ed0e0,Where to buy pontoon boat kits,025_creative_hobbyist,944346ce7b090355,False,False,base,,e24149386430f3b8,1,1,http://u-fabboats.com/
2528,b1ec2d4fc196a8fa,Best way to grow English Ivy,025_creative_hobbyist,944346ce7b090355,False,False,base,,27d749a29dcc404c,1,1,http://www.guide-to-houseplants.com/english-iv...
2529,af62766d7d794ab7,Paint kitchen cabinet,025_creative_hobbyist,944346ce7b090355,False,False,base,,64d752b278e135b6,1,1,http://thebestcabinetsite.com/paints/the-best-...
2530,0e95052dd86421a3,How to safely paint wooden cookware,025_creative_hobbyist,944346ce7b090355,False,False,base,,31651beedc3c13ca,1,1,https://snapguide.com/guides/paint-the-handles...
2531,4db8de5ed3518f41,Italian sausage,025_creative_hobbyist,944346ce7b090355,False,False,base,,554e5a8e024b581b,1,1,http://allrecipes.com/recipe/16539/italian-sty...
2532,41c2298412b671ee,Intermittent fasting,025_creative_hobbyist,944346ce7b090355,False,False,base,,edcdf2c9b3afc86b,1,1,https://en.wikipedia.org/wiki/Intermittent_fas...
2533,265058d46174bf38,Best budget for interlocking paver installation,025_creative_hobbyist,944346ce7b090355,False,False,base,,3112e5b7236e0782,1,1,http://homewyse.com/services/cost_to_install_i...
2534,6a645b8ca7be8e35,Steps to start a career in health psychology,025_creative_hobbyist,944346ce7b090355,False,False,base,,bccb33eeb349e2ac,1,1,http://careersinpsychology.org/becoming-a-heal...
2535,ee3422fb0bc42a91,Best tea,025_creative_hobbyist,944346ce7b090355,False,False,base,,5c03d345abdd08d5,1,1,http://www.bestproducts.com/eats/drinks/g208/b...
2536,0c16d8bb8dd8cfb8,Soil healthy,025_creative_hobbyist,944346ce7b090355,False,False,base,,458898866ef3a26f,1,1,https://www.thespruce.com/healthy-soil-and-how...

In [7]:
profile_df

,doc_id,url,title,description,frecency,last_visit_date,profile,profile_id,variant
82653,3b9332b3e77dcbaf,http://www.ehow.com/how_5409995_cook-fennel.html,How to Cook Fennel,"A decidedly odd-looking vegetable, fennel rese...",5000,1738272723614003,025_creative_hobbyist,944346ce7b090355,base
82654,c2a01b4478300d0f,http://www.phschool.com/language_arts/,Language Arts,Language Arts Student Resources Textbook Compa...,5000,1738272733950727,025_creative_hobbyist,944346ce7b090355,base
82655,5b4098fca631d4d5,https://www.8notes.com/biographies/adams.asp,Items to buy by Bryan Adams,Items to buy by Bryan Adams (Everything I Do) ...,4999,1738272724722098,025_creative_hobbyist,944346ce7b090355,base
82656,8eea7bb8edd43f0f,http://www.wikihow.com/Get-Rid-of-Mosquitoes-i...,How to Get Rid of Mosquitoes in Your Yard,1 Drain any areas with standing water. Mosquit...,4998,1738272735386823,025_creative_hobbyist,944346ce7b090355,base
82657,fa865024f44bc6a4,http://www.goddessgift.com/goddess-myths/godde...,Goddess Symbols: Hestia,Goddess Symbols: Hestia Goddess Symbols and Sa...,4997,1738272735282816,025_creative_hobbyist,944346ce7b090355,base
...,...,...,...,...,...,...,...,...,...
88900,c62fb10d4c75e929,http://www.cnn.com/2008/TRAVEL/traveltips/06/2...,How to get airport lounge discounts,By Andrea Bennett (Travel + Leisure) -- The fo...,107,1738272729266412,025_creative_hobbyist,944346ce7b090355,base
88901,fb630ebaf0bee9b7,https://www.diabetesselfmanagement.com/managin...,What Makes Blood Glucose Go Up or Down?,What Makes Blood Glucose Go Up or Down? Update...,106,1738272724750099,025_creative_hobbyist,944346ce7b090355,base
88902,fcac6fa5e6fa11e0,https://fit4less.ca/facts,Fit4Less Facts,Fit4Less Facts Membership Card You must have y...,105,1738272735062801,025_creative_hobbyist,944346ce7b090355,base
88903,4a80c9217a88c02d,https://blog.onestoppoppyshoppe.com/articles/p...,One Stop Poppy Shoppe Blog,Poppy Flower Seeds – Germinating and Growing P...,103,1738272734902791,025_creative_hobbyist,944346ce7b090355,base
88904,5aa8a8ced2dec332,https://www.askmen.com/top_10/entertainment/to...,Top 10: Celebrity Roasts,Top 10: Celebrity Roasts Geoffrey Lansdell Sha...,100,1738272723780018,025_creative_hobbyist,944346ce7b090355,base

In [8]:
%%time
profile_embeddings = model.encode(profile_df['title'].str.lower().values.tolist())

CPU times: user 162 ms, sys: 22.9 ms, total: 185 ms
Wall time: 65.7 ms

In [9]:


def search(query, model, profile_embeddings, profile_df, top_k=2, threshold=0.6):
    query_embeddings = model.encode([query])
    sim_scores = cosine_similarity(query_embeddings, profile_embeddings)[0]  # shape: (N,)

    valid_idx = np.where(sim_scores >= threshold)[0]
    if valid_idx.size == 0:
        return []

    ranked_idx = valid_idx[np.argsort(-sim_scores[valid_idx])[:top_k]]
    return profile_df.iloc[ranked_idx]['url'].tolist()

In [10]:
search("Best mosquito repellent outdoor", model, profile_embeddings, profile_df, top_k=5)
search("Zucchini recipes", model, profile_embeddings, profile_df, top_k=2)

['http://startcooking.com/how-to-zucchini',
 'http://allrecipes.com/recipe/233453/low-carb-zucchini-pasta/']

In [11]:
correct = 0
for idx, row in golden_queries_df.iterrows():
    actual = row['url']
    preds = search(row['search_query'].lower(), model, profile_embeddings, profile_df, top_k=3, threshold=0.5)
    if actual in preds:
        correct += 1
        
    # else:
    #     print(idx, row['search_query'], actual, preds)

In [12]:
correct

30

In [13]:
correct/len(golden_queries_df)

0.8108108108108109

In [14]:
## Results for creative_hobyist (38 queries)
## allXenova/all-MiniLM-L6-v2: 33 correct (0.84)
## minishlab/potion-retrieval-32M: 30 correct (0.78)

In [15]:
## Results for chidam (48 queries)
## allXenova/all-MiniLM-L6-v2: 17 correct (0.35)
## minishlab/potion-retrieval-32M: 20 correct (0.40)

#### Using long & short Q datasets and profiles

In [16]:
# longQ = [
#       "alternative medicine to manage ringing in my ear",
#       "solutions for noisy neighbors",
#       "how to train a cat to use the litter box",
#       "how to make your dog loss weight",
#       "what are the best foods for dogs",
#       "how to keep your kids safe online",
#       "some recommendations for vegan recipes for kids",
#       "best places to visit in new york in summer",
#       "how much does it cost to go to niagara falls",
#       "how to take screenshot on windows 11",
#       "what are some of the symptoms of high blood pressure",
#       "what are some treatment options for stroke",
#       "organic dog food for sensitive stomachs",
#       "best budget-friendly family vacation spots in California",
#       "what are some popular open source projects",
#     ]

# shortQ = [
#       "healthy rice",
#       "endodontist",
#       "arsenal",
#       "gavaskar border trophy",
#       "grand slam champion",
#       "capital gain",
#       "credit limit",
#       "annuity",
#       "physiology",
#       "myopia",
#       "amyloidosis",
#       "alopecia",
#       "dermatitis",
#       "coffee shop",
#       "ball drop",
#     ]

queries_longQ_longD = queries.loc[queries["profile"]=="longQ_longD"]
queries_shortQ_longD = queries.loc[queries["profile"]=="shortQ_longD"]

queries_longQ_shortD = queries.loc[queries["profile"]=="longQ_shortD"]
queries_shortQ_shortD = queries.loc[queries["profile"]=="shortQ_shortD"]

In [17]:
# len(longQ), len(shortQ)
len(queries_longQ_longD), len(queries_shortQ_longD), len(queries_longQ_shortD), len(queries_shortQ_shortD)

(15, 15, 15, 15)

In [18]:
# lonQ_longD_file_path = "../test_data/longQ_longD.json"
# lonQ_shortD_file_path = "../test_data/longQ_shortD.json"

# shortQ_longD_file_path = "../test_data/shortQ_longD.json"
# shortQ_shortD_file_path = "../test_data/shortQ_shortD.json"

In [19]:
# lonQ_longD_df = pd.read_json(lonQ_longD_file_path)[PROFILE_COLS]
# lonQ_shortD_df = pd.read_json(lonQ_shortD_file_path)[PROFILE_COLS]

# shortQ_longD_df = pd.read_json(shortQ_longD_file_path)[PROFILE_COLS]
# shortQ_shortD_df = pd.read_json(shortQ_shortD_file_path)[PROFILE_COLS]

lonQ_longD_df = docs.loc[docs["profile"] == "longQ_longD"]
lonQ_shortD_df = docs.loc[docs["profile"] == "longQ_shortD"]
shortQ_longD_df = docs.loc[docs["profile"] == "shortQ_longD"]
shortQ_shortD_df = docs.loc[docs["profile"] == "shortQ_shortD"]


lonQ_longD_df.shape, lonQ_shortD_df.shape, shortQ_longD_df.shape, shortQ_shortD_df.shape

((8743, 9), (7411, 9), (8717, 9), (7444, 9))

In [20]:
lonQ_longD_df[:36]

,doc_id,url,title,description,frecency,last_visit_date,profile,profile_id,variant
88905,8bf825df90d583f7,https://www.buoyhealth.com/symptoms-a-z/ringin...,"Ringing in the Ears Symptoms, Causes & Treatme...","Ringing in the Ears Symptoms, Causes & Treatme...",1421560,1736196807185413,longQ_longD,9c27e185d18e183a,length-variants
88906,a09ef53a5b37d6c4,https://www.necksolutions.com/tinnitus.html,Tinnitus Is Often Described As Ringing In The ...,Tinnitus Is Often Described As Ringing In The ...,281700,1736189753947959,longQ_longD,9c27e185d18e183a,length-variants
88907,1261bcedfb073438,https://www.legalzoom.com/articles/neighbor-di...,Neighbor Disputes: What to Do When Your Neighb...,Neighbor Disputes: What to Do When Your Neighb...,274017,1736176190746123,longQ_longD,9c27e185d18e183a,length-variants
88908,082a5ff5b004238b,https://answers.yahoo.com/question/index?qid=2...,"My Microwave is making a loud humming noise, c...",Home & Garden Maintenance & Repairs My Microwa...,248551,1736176755662276,longQ_longD,9c27e185d18e183a,length-variants
88909,7dbf634bacf2cefb,http://www.drsfostersmith.com/pic/article.cfm?...,Frequently Asked Questions about Feline Litter...,Frequently Asked Questions about Feline Litter...,236911,1735422684696590,longQ_longD,9c27e185d18e183a,length-variants
88910,633bccf2f6ecc1f6,https://www.drelseys.com/2015/05/08/how-often-...,Our Blog ::: How Often Should I Change the Lit...,"May 8, 2015How Often Should I Change the Litte...",203868,1734619916609214,longQ_longD,9c27e185d18e183a,length-variants
88911,919a39037c9b416c,https://answers.yahoo.com/question/index?qid=2...,How do you show your dog your a pack leader?,Pets Dogs How do you show your dog your a pack...,157336,1734757831526359,longQ_longD,9c27e185d18e183a,length-variants
88912,6bd7e1ab5ad77fba,http://www.vetwest.com.au/pet-library/weight-t...,Weight - the ideal bodyweight range for your d...,Weight - the ideal bodyweight range for your d...,84530,1735835977907487,longQ_longD,9c27e185d18e183a,length-variants
88913,a0de36e9962a78f0,http://www.dogfoodscoop.com/10-best-dog-food.html,Top 10 Best Dog Food Our Pick of the Best Dry ...,Top 10 Best Dog Food Our Pick of the Best Dry ...,83355,1735829441460524,longQ_longD,9c27e185d18e183a,length-variants
88914,3668678172562360,http://animals.howstuffworks.com/pets/10-fruit...,10 Fruits and Veggies that Aid in Dogs' Nutrition,NEXTStart the Countdown Those farmstand vegeta...,80600,1736177187460005,longQ_longD,9c27e185d18e183a,length-variants
88915,47fdb82b29eb3b56,http://thecarseatlady.com/warmandsafe/,Weâve got lots of suggestions below for ways t...,Keep Kids WARM AND SAFE in the Car Seat Posted...,76140,1736175921800935,longQ_longD,9c27e185d18e183a,length-variants
88916,4eee25af33a71c2b,https://www.verywellfamily.com/things-to-teach...,5 Things to Teach Your Kids About Digital Etiq...,Bullying5 Things to Teach Your Kids About Digi...,74200,1736181504226041,longQ_longD,9c27e185d18e183a,length-variants
88917,98366adce6c7c95a,http://www.vegancoach.com/vegan-baking.html,Perfect Your Vegan Baking Skills With These Ti...,Home > Cooking Techniques > Vegan Baking Perfe...,63579,1733351518443266,longQ_longD,9c27e185d18e183a,length-variants
88918,5827a954c8f277ce,http://www.theveganwoman.com/is-vegan-food-mor...,Is Vegan Food More Expensive? A Guide to Eatin...,Is Vegan Food More Expensive? A Guide to Eatin...,61179,1732290559643847,longQ_longD,9c27e185d18e183a,length-variants
88919,5a4e54d2287b5d80,http://newyork.seriouseats.com/2012/04/visitin...,"Visiting NYC? Where to Eat in New York, the Be...","Visiting NYC? Where to Eat in New York, the Be...",58104,1733519754162940,longQ_longD,9c27e185d18e183a,length-variants
88920,f8e50311a469b7f2,http://brooklyn.about.com/od/Free-Cheap-Fun-in...,When are the Summer Fireworks in Coney Island?,By Ellen Freudenheim Updated 05/16/17Share Pin...,57077,1732727264793078,longQ_longD,9c27e185d18e183a,length-variants
88921,dac9a0abc58a4436,http://www.todocanada.ca/niagara-falls-day-one...,Niagara Falls in a Day â One Day Trip to Niaga...,"Planning a one day trip to see the glorious, s...",55923,1733847803964658,longQ_longD,9c27e185d18e183a,length-variants
88922,3561ccda7f7082f7,https://www.viator.com/Niagara-Falls-and-Aroun...,"Niagara Falls & Around Tours, Tickets, Activit...","Niagara Falls & Around Tours, Tickets, Activit...",54111,1735419476979987,longQ_longD,9c27e185d18e183a,length-variants
88923,5c5d59f9ff2d7b70,https://app.prntscr.com/,The fastest way to take a customizable screenshot,Download for Windows Download for Mac The fast...,50700,1736195992432400,longQ_longD,9c27e185d18e183a,length-variants
88924,a1bb489f29953737,https://www2.owens.edu/faq/entry/66/,How do I take a screenshot (picture of my comp...,How do I take a screenshot (picture of my comp...,48000,1736175784781764,longQ_longD,9c27e185d18e183a,length-variants
88925,ca12ae2820b01462,http://www.emedicinehealth.com/high_blood_pres...,"High Blood Pressure (Symptoms, Signs, Causes, ...",What Is High Blood Pressure? What Do Blood Pre...,46526,1734018516879882,longQ_longD,9c27e185d18e183a,length-variants
88926,8af48818cde4b025,http://www.mayoclinic.org/diseases-conditions/...,High blood pressure dangers: Hypertension's ef...,High blood pressure dangers: Hypertension's ef...,44500,1736189802236131,longQ_longD,9c27e185d18e183a,length-variants
88927,ab0b038a6195404f,http://stroke.emedtv.com/plavix/generic-plavix...,Is Generic Clopidogrel Equivalent to the Brand...,Stroke Channel Topics & Medications Ischemic S...,40430,1734716394468418,longQ_longD,9c27e185d18e183a,length-variants
88928,9b5ce07cac10b6a0,http://www.mayoclinic.org/diseases-conditions/...,Stroke rehabilitation: What to expect as you r...,Stroke rehabilitation: What to expect as you r...,40131,1734757831263925,longQ_longD,9c27e185d18e183a,length-variants
88929,2224d6f1d51cf9ec,http://www.answers.com/Q/What_is_the_nutrition...,What is the nutritional difference between pup...,Answers.com ® Wiki Answers ® Categories Animal...,40124,1735420424607452,longQ_longD,9c27e185d18e183a,length-variants
88930,6f59d70331e754df,http://doggonest.com/blue-buffalo-dog-food/,Blue Buffalo Dog Food: Choosing a Commercial P...,Blue Buffalo Dog Food: Choosing a Commercial P...,35750,1736178121270154,longQ_longD,9c27e185d18e183a,length-variants
88931,60ce7dcf3d15930e,http://www.wildwoodsnj.com/wildwood-boardwalk-...,A beach vacation destination like none other,A beach vacation destination like none other P...,35162,1734636640791283,longQ_longD,9c27e185d18e183a,length-variants
88932,587d8c7b10927376,http://allseasonsvacationrents.com/Unit/Detail...,All Seasons Vacation Rentals is Your Home Away...,All Seasons Vacation Rentals is Your Home Away...,32300,1736196994496593,longQ_longD,9c27e185d18e183a,length-variants
88933,3cded66c9c24e7f8,http://www.webopedia.com/quick_ref/free-web-an...,30 Free Web Tools and Open Source Software for...,Main » Quick Reference »30 Free Web Tools and ...,30566,1734019709682735,longQ_longD,9c27e185d18e183a,length-variants
88934,f5309ea2e4688404,http://alternativeto.net/software/maple/?licen...,Alternativesto Maple for all platformswith Ope...,Alternativesto Maple for all platformswith Ope...,29952,1736175970209597,longQ_longD,9c27e185d18e183a,length-variants
88935,1488e619fcf44056,https://www.washingtonpost.com/blogs/erik-wemp...,Why does CNN commentator Jeffrey Lord say such...,(Screenshot)CNN political commentator Jeffrey...,29055,1736176194944227,longQ_longD,9c27e185d18e183a,length-variants
88936,59e989588eb4b729,https://support.apple.com/kb/PH2639,iCloud: Open or download email attachments in ...,A message that contains an attachment has a pa...,26946,1734464997729841,longQ_longD,9c27e185d18e183a,length-variants
88937,faad5cb5aaa01533,https://www.payscale.com/compensation-today/20...,The Importance of Creating a Salary Benchmarki...,"May 15, 2009The Importance of Creating a Salar...",26117,1734620270564132,longQ_longD,9c27e185d18e183a,length-variants
88938,efea4460444e4ebc,http://www.answers.com/Q/Is_the_water_from_a_c...,Is the water from a condensing tumble dryer di...,Answers.com ® Wiki Answers ® Categories Busine...,24118,1732643770587588,longQ_longD,9c27e185d18e183a,length-variants
88939,233280aa5a7b815a,http://www.lyonsswimclub.com/Swim_Team/Coaches...,Head Coach and National Team Coach â Casey Hna...,Head Coach and National Team Coach – Casey Hna...,22613,1734099802405693,longQ_longD,9c27e185d18e183a,length-variants
88940,431c5ea5f8a1c4f5,https://phys.org/news/2011-07-gyroscope-unexpl...,Gyroscope's unexplained acceleration may be du...,"Home Physics General Physics July 26, 2011Gyro...",21960,1735918964724223,longQ_longD,9c27e185d18e183a,length-variants

In [21]:
def search_long_short_queries(query_id, model, profile_embeddings, profile_df, top_k=2, threshold=0.6):
    query_details = queries.loc[queries["query_id"]==query_id]
    query = query_details["search_query"].item()

    q_docs = query_pairs.loc[query_pairs["query_id"]==query_id][["doc_id", "rank", "relevance"]].sort_values("rank", ascending=True)
    
    query_embeddings = model.encode([query])
    sim_scores = cosine_similarity(query_embeddings, profile_embeddings)[0]

    valid_idx = np.where(sim_scores >= threshold)[0]
    ranked_idx = valid_idx[np.argsort(-sim_scores[valid_idx])[:top_k]]
    
    if valid_idx.size == 0:
        return []
    
    res = []
    for idx in ranked_idx:
        res.append(profile_df.iloc[idx])

    doc_ids = set(q_docs["doc_id"].astype(str))

    has_overlap = any(str(p.doc_id) in doc_ids for p in res)
    return has_overlap
    
    # ranked_idx = valid_idx[np.argsort(-sim_scores[valid_idx])[:top_k]]
    # return profile_df.iloc[ranked_idx]['url'].tolist()

In [22]:
lonQ_longD_profile_embeddings = model.encode(lonQ_longD_df['title'].str.lower() + " " + lonQ_longD_df['description'].str.lower())
print(lonQ_longD_profile_embeddings.shape)
correct_longQ_longD = 0
for qid in queries_longQ_longD["query_id"]:
    res = search_long_short_queries(qid, model, lonQ_longD_profile_embeddings, lonQ_longD_df, top_k=2, threshold=0.6)
    if res:
        correct_longQ_longD += 1

print("correct_longQ_longD", correct_longQ_longD)
print("correct percentage", round(correct_longQ_longD/len(queries_longQ_longD), 3))

(8743, 512)
correct_longQ_longD 10
correct percentage 0.667

In [23]:
lonQ_shortD_profile_embeddings = model.encode(lonQ_shortD_df['title'].str.lower() + " " + lonQ_shortD_df['description'].str.lower())
print(lonQ_shortD_profile_embeddings.shape)
correct_longQ_shortD = 0
for qid in queries_longQ_shortD["query_id"]:
    res = search_long_short_queries(qid, model, lonQ_shortD_profile_embeddings, lonQ_shortD_df, top_k=2, threshold=0.6)
    if res:
        correct_longQ_shortD += 1

print("correct_longQ_shortD", correct_longQ_shortD)
print("correct percentage", round(correct_longQ_shortD/len(queries_longQ_shortD), 3))

(7411, 512)
correct_longQ_shortD 14
correct percentage 0.933

In [24]:
shortQ_longD_profile_embeddings = model.encode(shortQ_longD_df['title'].str.lower() + " " + shortQ_longD_df['description'].str.lower())
print(shortQ_longD_profile_embeddings.shape)
correct_shortQ_longD = 0
for qid in queries_shortQ_longD["query_id"]:
    res = search_long_short_queries(qid, model, shortQ_longD_profile_embeddings, shortQ_longD_df, top_k=2, threshold=0.6)
    if res:
        correct_shortQ_longD += 1

print("correct_shortQ_longD", correct_shortQ_longD)
print("correct percentage", round(correct_shortQ_longD/len(queries_shortQ_longD), 3))

(8717, 512)
correct_shortQ_longD 10
correct percentage 0.667

In [25]:
shortQ_shortD_profile_embeddings = model.encode(shortQ_shortD_df['title'].str.lower() + " " + shortQ_shortD_df['description'].str.lower())
print(shortQ_shortD_profile_embeddings.shape)
correct_shortQ_shortD = 0
for qid in queries_shortQ_shortD["query_id"]:
    res = search_long_short_queries(qid, model, shortQ_shortD_profile_embeddings, shortQ_shortD_df, top_k=2, threshold=0.6)
    if res:
        correct_shortQ_shortD += 1

print("correct_shortQ_longD", correct_shortQ_shortD)
print("correct percentage", round(correct_shortQ_shortD/len(queries_shortQ_shortD), 3))

(7444, 512)
correct_shortQ_longD 14
correct percentage 0.933

In [26]:
## store these in sqlite-vec DB

In [27]:
import numpy as np
import sqlite3
import sqlite_vec

from typing import List
import struct

In [28]:
def serialize_f32(vector: List[float]) -> bytes:
    """serializes a list of floats into a compact "raw bytes" format"""
    return struct.pack("%sf" % len(vector), *vector)

In [29]:
db = sqlite3.connect(":memory:")
db.enable_load_extension(True)
sqlite_vec.load(db)
db.enable_load_extension(False)

sqlite_version, vec_version = db.execute(
    "select sqlite_version(), vec_version()"
).fetchone()
print(f"sqlite_version={sqlite_version}, vec_version={vec_version}")

sqlite_version=3.50.2, vec_version=v0.1.6

In [30]:
lonQ_shortD_profile_embeddings.shape

(7411, 512)

In [31]:
persona = "lonQ_shortD"
EMBEDDING_SIZE = lonQ_shortD_profile_embeddings.shape[1]
db.execute(f"CREATE VIRTUAL TABLE vec_items_{persona}_2 USING vec0(embedding float[{EMBEDDING_SIZE}], embedding_coarse bit[{EMBEDDING_SIZE}])")

with db:
    for idx, vec in enumerate(lonQ_shortD_profile_embeddings):
        embedding = serialize_f32(vec)
        db.execute(
            f"INSERT INTO vec_items_{persona}_2(rowid, embedding, embedding_coarse) VALUES (?, ?, vec_quantize_binary(?))",
            [idx, embedding, embedding],  # Convert vector to binary format
        )

In [32]:
# longQ
longQ = queries_longQ_shortD["search_query"].to_list()
longQ

['alternative medicine to manage ringing in my ear',
 'solutions for noisy neighbors',
 'how to train a cat to use the litter box',
 'how to make your dog loss weight',
 'what are the best foods for dogs',
 'how to keep your kids safe online',
 'some recommendations for vegan recipes for kids',
 'best places to visit in new york in summer',
 'how much does it cost to go to niagara falls',
 'how to take screenshot on windows 11',
 'what are some of the symptoms of high blood pressure',
 'what are some treatment options for stroke',
 'organic dog food for sensitive stomachs',
 'best budget-friendly family vacation spots in California',
 'what are some popular open source projects']

In [33]:
def predict_coarse(query, lonQ_shortD_df):
    query_serialized_vec = serialize_f32(model.encode(query))
    
    retrived_results = db.execute(f"""
    with coarse_matches as (
      select
        rowid,
        embedding
      from vec_items_{persona}_2
      where embedding_coarse match vec_quantize_binary(:query_serialized_vec)
      and k=200
      order by distance
      
    )
    select
      rowid,
      vec_distance_cosine(embedding, :query_serialized_vec)
    from coarse_matches
    order by 2
    limit 2;
    """, {"query_serialized_vec": query_serialized_vec}).fetchall()
    print(retrived_results)
    return lonQ_shortD_df.iloc[[row for row,dist in retrived_results]]

In [34]:
query = longQ[0]
print(query)
predict_coarse(query, lonQ_shortD_df)

alternative medicine to manage ringing in my ear
[(1, 0.33442482352256775), (0, 0.33442482352256775)]

,doc_id,url,title,description,frecency,last_visit_date,profile,profile_id,variant
97649,a788f65f05c5ee76,http://www.rightdiagnosis.com/sym/ringing_in_e...,Ringing in ears,,281700,1736189753947959,longQ_shortD,167eb560a6601afc,length-variants
97648,06647eed20905bfb,http://symptomchecker.webmd.com/single-symptom...,Ringing in ears,,1421560,1736196807185413,longQ_shortD,167eb560a6601afc,length-variants